BEGIN TRANSACTION;
INSERT INTO command_definitions VALUES('ai.addignoreplayer','Addignoreplayer','Add a player (or command user if no player is specified) to the AIs ignore list.','ai',0,0,1);
INSERT INTO command_definitions VALUES('ai.aizonestats','Aizonestats',NULL,'ai',0,0,1);
INSERT INTO command_definitions VALUES('ai.brainstats','Brainstats',NULL,'ai',0,0,1);
INSERT INTO command_definitions VALUES('ai.clearignoredplayers','Clearignoredplayers','Remove all players from the AIs ignore list.','ai',1,0,1);
INSERT INTO command_definitions VALUES('ai.killanimals','Killanimals',NULL,'ai',0,0,1);
INSERT INTO command_definitions VALUES('ai.killscientists','Killscientists',NULL,'ai',0,0,1);
INSERT INTO command_definitions VALUES('ai.printignoredplayers','Printignoredplayers','Print a lost of all the players in the AI ignore list.','ai',0,0,1);
INSERT INTO command_definitions VALUES('ai.printorkilloffnavscientists','Printorkilloffnavscientists','Print a list of all scientists that are off the navmesh. Optionally kill them off by passing true as the first argument.','ai',1,0,1);
INSERT INTO command_definitions VALUES('ai.removeignoreplayer','Removeignoreplayer','Remove a player (or command user if no player is specified) from the AIs ignore list.','ai',1,0,1);
INSERT INTO command_definitions VALUES('ai.selectnpclookatserver','Selectnpclookatserver',NULL,'ai',0,0,1);
INSERT INTO command_definitions VALUES('ai.setnpcreactiontime','Setnpcreactiontime','The time it takes for a NPC to fully notice a player standing right in front of them, in seconds.','ai',0,0,1);
INSERT INTO command_definitions VALUES('ai.showdistributions','Showdistributions',NULL,'ai',0,0,1);
INSERT INTO command_definitions VALUES('ai.showstate','Showstate',NULL,'ai',0,0,1);
INSERT INTO command_definitions VALUES('ai.sleepwakestats','Sleepwakestats',NULL,'ai',0,0,1);
INSERT INTO command_definitions VALUES('ai.wakesleepingai','Wakesleepingai',NULL,'ai',0,0,1);
INSERT INTO command_definitions VALUES('analytics.pending_analytics','Pending Analytics','Shows how many analytics events are pending upload','analytics',0,0,1);
INSERT INTO command_definitions VALUES('analytics.resetstats','Resetstats',NULL,'analytics',0,0,1);
INSERT INTO command_definitions VALUES('analytics.stats','Stats',NULL,'analytics',0,0,1);
INSERT INTO command_definitions VALUES('analytics.tablestats','Tablestats',NULL,'analytics',0,0,1);
INSERT INTO command_definitions VALUES('analytics.uploaderstats','Uploaderstats',NULL,'analytics',0,0,1);
INSERT INTO command_definitions VALUES('app.appban','Appban',NULL,'app',0,0,1);
INSERT INTO command_definitions VALUES('app.appunban','Appunban',NULL,'app',0,0,1);
INSERT INTO command_definitions VALUES('app.info','Info',NULL,'app',0,0,1);
INSERT INTO command_definitions VALUES('app.pair','Pair',NULL,'app',0,0,1);
INSERT INTO command_definitions VALUES('app.regeneratetoken','Regeneratetoken',NULL,'app',0,0,1);
INSERT INTO command_definitions VALUES('app.retry_initialize','Retry Initialize','Retry initializing the Rust+ companion server if it previously failed','app',0,0,1);
INSERT INTO command_definitions VALUES('ballistagun.reload','Reload',NULL,'ballistagun',0,0,1);
INSERT INTO command_definitions VALUES('baseboat.seconds_between_shore_drift','Seconds Between Shore Drift',NULL,'baseboat',0,0,1);
INSERT INTO command_definitions VALUES('baseboat.seconds_until_shore_drift','Seconds Until Shore Drift',NULL,'baseboat',0,0,1);
INSERT INTO command_definitions VALUES('basemission.profilenextmissionsvalidstateworkqueue','Profilenextmissionsvalidstateworkqueue','Generate a performance capture containing the next run of updateMissionValidStateWorkQueue','basemission',0,0,1);
INSERT INTO command_definitions VALUES('batteringramhead.hurt','Hurt',NULL,'batteringramhead',0,0,1);
INSERT INTO command_definitions VALUES('boatbuildingstation.print_stats','Print Stats',NULL,'boatbuildingstation',0,0,1);
INSERT INTO command_definitions VALUES('boombox.clearradiobyuser','Clearradiobyuser',NULL,'boombox',0,0,1);
INSERT INTO command_definitions VALUES('bot.crouch_server','Crouch Server',NULL,'bot',0,0,1);
INSERT INTO command_definitions VALUES('bot.sv_exec_command','Sv Exec Command',NULL,'bot',0,0,1);
INSERT INTO command_definitions VALUES('bot.sv_exec_command_all','Sv Exec Command All',NULL,'bot',0,0,1);
INSERT INTO command_definitions VALUES('bot.sv_exec_command_sphere','Sv Exec Command Sphere',NULL,'bot',0,0,1);
INSERT INTO command_definitions VALUES('bradley.quickrespawn','Quickrespawn',NULL,'bradley',0,0,1);
INSERT INTO command_definitions VALUES('bradleyapc.spawnroadbradley','Spawnroadbradley',NULL,'bradleyapc',0,0,1);
INSERT INTO command_definitions VALUES('camerarenderermanager.pool_stats','Pool Stats',NULL,'camerarenderermanager',0,0,1);
INSERT INTO command_definitions VALUES('cannon.adminfire','Adminfire',NULL,'cannon',0,0,1);
INSERT INTO command_definitions VALUES('cargoship.debug_cargo_status','Debug Cargo Status',NULL,'cargoship',0,0,1);
INSERT INTO command_definitions VALUES('cargoship.debug_info','Debug Info',NULL,'cargoship',0,0,1);
INSERT INTO command_definitions VALUES('cargoship.egress','Egress',NULL,'cargoship',0,0,1);
INSERT INTO command_definitions VALUES('cassette.clearcassettes','Clearcassettes',NULL,'cassette',0,0,1);
INSERT INTO command_definitions VALUES('cassette.clearcassettesbyuser','Clearcassettesbyuser',NULL,'cassette',0,0,1);
INSERT INTO command_definitions VALUES('catapult.fire','Fire','Fire all catapults','catapult',0,0,1);
INSERT INTO command_definitions VALUES('catapult.reload','Reload','Reload all catapults. 0: empty, 1: stone boulder, 2: fire bomb, 3: propane explosive, 4: bee bomb, 5: bot player','catapult',0,0,1);
INSERT INTO command_definitions VALUES('ch47helicopteraicontroller.dropcrate','Dropcrate',NULL,'ch47helicopteraicontroller',0,0,1);
INSERT INTO command_definitions VALUES('chat.cardgamesay','Cardgamesay',NULL,'chat',0,0,1);
INSERT INTO command_definitions VALUES('chat.clansay','Clansay',NULL,'chat',0,0,1);
INSERT INTO command_definitions VALUES('chat.localsay','Localsay',NULL,'chat',0,0,1);
INSERT INTO command_definitions VALUES('chat.say','Say',NULL,'chat',0,0,1);
INSERT INTO command_definitions VALUES('chat.search','Search',NULL,'chat',0,0,1);
INSERT INTO command_definitions VALUES('chat.tail','Tail',NULL,'chat',0,0,1);
INSERT INTO command_definitions VALUES('chat.teamsay','Teamsay',NULL,'chat',0,0,1);
INSERT INTO command_definitions VALUES('cinematicentity.hideobjects','Hideobjects','Hides cinematic entities by group (0= none, 1= lights, 2= BGs, 3= props, 4= misc)','cinematicentity',0,0,1);
INSERT INTO command_definitions VALUES('clan.info','Info','Prints info about a clan given its ID','clan',0,0,1);
INSERT INTO command_definitions VALUES('clawmarkspawner.showclawmarks','Showclawmarks',NULL,'clawmarkspawner',0,0,1);
INSERT INTO command_definitions VALUES('commands.echo','Echo',NULL,'commands',0,0,1);
INSERT INTO command_definitions VALUES('commands.find','Find',NULL,'commands',0,0,1);
INSERT INTO command_definitions VALUES('console.search','Search',NULL,'console',0,0,1);
INSERT INTO command_definitions VALUES('console.tail','Tail',NULL,'console',0,0,1);
INSERT INTO command_definitions VALUES('copypaste.copybox_sv','Copybox Sv',NULL,'copypaste',0,0,1);
INSERT INTO command_definitions VALUES('copypaste.copybuilding_sv','Copybuilding Sv',NULL,'copypaste',0,0,1);
INSERT INTO command_definitions VALUES('copypaste.copyradius_sv','Copyradius Sv',NULL,'copypaste',0,0,1);
INSERT INTO command_definitions VALUES('copypaste.download_paste','Download Paste',NULL,'copypaste',0,0,1);
INSERT INTO command_definitions VALUES('copypaste.killbox_sv','Killbox Sv',NULL,'copypaste',0,0,1);
INSERT INTO command_definitions VALUES('copypaste.list_pastes_sv','List Pastes Sv',NULL,'copypaste',0,0,1);
INSERT INTO command_definitions VALUES('copypaste.printselection_sv','Printselection Sv',NULL,'copypaste',0,0,1);
INSERT INTO command_definitions VALUES('copypaste.undopaste_sv','Undopaste Sv',NULL,'copypaste',0,0,1);
INSERT INTO command_definitions VALUES('craft.add','Add',NULL,'craft',0,0,1);
INSERT INTO command_definitions VALUES('craft.cancel','Cancel',NULL,'craft',0,0,1);
INSERT INTO command_definitions VALUES('craft.canceltask','Canceltask',NULL,'craft',0,0,1);
INSERT INTO command_definitions VALUES('craft.fasttracktask','Fasttracktask',NULL,'craft',0,0,1);
INSERT INTO command_definitions VALUES('creative.togglealwayson','Togglealwayson',NULL,'creative',0,0,1);
INSERT INTO command_definitions VALUES('creative.togglealwaysonall','Togglealwaysonall',NULL,'creative',0,0,1);
INSERT INTO command_definitions VALUES('creative.togglealwaysonradius','Togglealwaysonradius',NULL,'creative',0,0,1);
INSERT INTO command_definitions VALUES('creative.togglecreativemodeuser','Togglecreativemodeuser',NULL,'creative',0,0,1);
INSERT INTO command_definitions VALUES('cui.cui_test','Cui Test',NULL,'cui',0,0,1);
INSERT INTO command_definitions VALUES('cui.cui_test_update','Cui Test Update',NULL,'cui',0,0,1);
INSERT INTO command_definitions VALUES('cui.endtest','Endtest',NULL,'cui',0,0,1);
INSERT INTO command_definitions VALUES('data.export','Export',NULL,'data',0,0,1);
INSERT INTO command_definitions VALUES('ddraw.ddrawother','Ddrawother',NULL,'ddraw',0,0,1);
INSERT INTO command_definitions VALUES('debug.applybuildingblockrandomisation','Applybuildingblockrandomisation',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.applypuzzleresettime','Applypuzzleresettime',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.bench_io','Bench Io','Spawn lots of IO entities to lag the server','debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.breakheld','Breakheld','Break the current held object','debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.breakheld_almost','Breakheld Almost','Almost break the current held object','debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.breakitem','Breakitem','Break all the items in your inventory whose name match the passed string','debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.breakshield','Breakshield','Breaks the currently held shield','debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.clearplayermodifiers','Clearplayermodifiers',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.cleartutorialforplayer','Cleartutorialforplayer','If a player ends up stuck on a tutorial for any reason this will clear the island and reset the player (will also kill player)','debug',1,0,1);
INSERT INTO command_definitions VALUES('debug.completemission','Completemission',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.completemissionstage','Completemissionstage',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.completetutorial','Completetutorial',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.console_print_color','Console Print Color',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.console_spam','Console Spam',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.conveyorstrictmodereport','Conveyorstrictmodereport',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.deleteentitiesbyshortname','Deleteentitiesbyshortname','<shortname> (optional: <radius>) - Delete entities with the given short prefab name','debug',1,0,1);
INSERT INTO command_definitions VALUES('debug.deleteentitybyid','Deleteentitybyid','Delete entities by id. Supports multiple arguments','debug',1,0,1);
INSERT INTO command_definitions VALUES('debug.drink','Drink',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.dropworlditems','Dropworlditems',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.eat','Eat',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.enable_player_movement','Enable Player Movement',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.fillmounts','Fillmounts','fillmounts <radius> - Spawns and mounts a player on every mount point in radius','debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.flushgroup','Flushgroup','Takes you in and out of your current network group, causing you to delete and then download all entities in your PVS again','debug',1,0,1);
INSERT INTO command_definitions VALUES('debug.foodspoilingdeducttimehours','Foodspoilingdeducttimehours','Deducts the given number of hours from all spoilable food on the server','debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.foodspoilinginventoryhours','Foodspoilinginventoryhours','Applies the given number of hours to all food in the players inventory','debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.foodspoilingspoilall','Foodspoilingspoilall','Spoils all food on the server','debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.forcechickensspawnegg','Forcechickensspawnegg',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.heal','Heal','To disable revival if player is downed, pass in --no-recover as the first argument.','debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.hurt','Hurt',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.invis','Invis','Make admin invisible','debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.print_topologies','Print Topologies','Prints out the topologies at your position','debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.printgrouplayer','Printgrouplayer',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.printgroups','Printgroups',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.printqueues','Printqueues',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.puzzlereset','Puzzlereset','Reset all puzzles. Optionally provide a number to only reset puzzles within a radius.','debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.puzzleresetinfo','Puzzleresetinfo',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.quittutorial','Quittutorial',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.refillvitals','Refillvitals','Refills the vital of a target player. eg. debug.refillsvital jim - leave blank to target yourself, can take multiple players at once. Will revive players if they are injured. To disable this, pass in --no-recover as the first argument.','debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.refillvitalsall','Refillvitalsall','Refills the vitals of all active players on the server. Will revive players if they are injured. To disable this, pass in --no-recover as the first argument.','debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.removeoverlappingstaticspawnpoints','Removeoverlappingstaticspawnpoints',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.renderinfo','Renderinfo',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.repair_inventory','Repair Inventory','Repair all items in inventory','debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.resetsleepingbagtimers','Resetsleepingbagtimers',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.respawnvinetreesinradius','Respawnvinetreesinradius',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.setdamage','Setdamage',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.setfood','Setfood',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.sethealth','Sethealth',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.setmaxhealth','Setmaxhealth',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.setradiation','Setradiation',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.setthrowable','Setthrowable','0 = can''t throw, 1 = can throw & melee, 2 = only throwable','debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.setunloadablecarfillpercent','Setunloadablecarfillpercent',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.setwater','Setwater',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.spawn_all_deployables','Spawn All Deployables','Spawns one of every deployable in a grid','debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.spawnovenstresstest','Spawnovenstresstest',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.spawnparachutetester','Spawnparachutetester',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.stall','Stall',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.starttutorial','Starttutorial',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.test_custom_vitals','Test Custom Vitals',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.testtutorialcinematic','Testtutorialcinematic',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.tutorialstatus','Tutorialstatus',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.vineswinginghighlight','Vineswinginghighlight',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('debug.vineswingingreport','Vineswingingreport',NULL,'debug',0,0,1);
INSERT INTO command_definitions VALUES('deepsea.close','Close',NULL,'deepsea',0,0,1);
INSERT INTO command_definitions VALUES('deepsea.createdeepsea','Createdeepsea',NULL,'deepsea',0,0,1);
INSERT INTO command_definitions VALUES('deepsea.enterdeepsea','Enterdeepsea',NULL,'deepsea',0,0,1);
INSERT INTO command_definitions VALUES('deepsea.leavedeepsea','Leavedeepsea',NULL,'deepsea',0,0,1);
INSERT INTO command_definitions VALUES('deepsea.open','Open',NULL,'deepsea',0,0,1);
INSERT INTO command_definitions VALUES('deepsea.printentitycount','Printentitycount',NULL,'deepsea',0,0,1);
INSERT INTO command_definitions VALUES('deepsea.printloot','Printloot',NULL,'deepsea',0,0,1);
INSERT INTO command_definitions VALUES('deepsea.printtimetowipe','Printtimetowipe',NULL,'deepsea',0,0,1);
INSERT INTO command_definitions VALUES('deepsea.settimetonextopening','Settimetonextopening',NULL,'deepsea',0,0,1);
INSERT INTO command_definitions VALUES('deepsea.settimetowipe','Settimetowipe',NULL,'deepsea',0,0,1);
INSERT INTO command_definitions VALUES('deepsea.spawnfloatingcityhere','Spawnfloatingcityhere',NULL,'deepsea',0,0,1);
INSERT INTO command_definitions VALUES('deepsea.spawnghostshiphere','Spawnghostshiphere',NULL,'deepsea',0,0,1);
INSERT INTO command_definitions VALUES('deepsea.spawnislandhere','Spawnislandhere',NULL,'deepsea',0,0,1);
INSERT INTO command_definitions VALUES('deepsea.spawnrhibgrouphere','Spawnrhibgrouphere',NULL,'deepsea',0,0,1);
INSERT INTO command_definitions VALUES('deepsea.status','Status',NULL,'deepsea',0,0,1);
INSERT INTO command_definitions VALUES('deepsea.testportalspawnlocation','Testportalspawnlocation',NULL,'deepsea',0,0,1);
INSERT INTO command_definitions VALUES('demo.record','Record',NULL,'demo',0,0,1);
INSERT INTO command_definitions VALUES('demo.stop','Stop',NULL,'demo',0,0,1);
INSERT INTO command_definitions VALUES('electricbattery.batteryid','Batteryid',NULL,'electricbattery',0,0,1);
INSERT INTO command_definitions VALUES('entity.debug_toggle','Debug Toggle',NULL,'entity',0,0,1);
INSERT INTO command_definitions VALUES('entity.deleteby','Deleteby','Destroy all entities created by provided users (separate users by space)','entity',1,0,1);
INSERT INTO command_definitions VALUES('entity.deletebytextblock','Deletebytextblock','Destroy all entities created by users in the provided text block (can use with copied results from ent auth)','entity',1,0,1);
INSERT INTO command_definitions VALUES('entity.find_entity','Find Entity',NULL,'entity',0,0,1);
INSERT INTO command_definitions VALUES('entity.find_group','Find Group',NULL,'entity',0,0,1);
INSERT INTO command_definitions VALUES('entity.find_id','Find Id',NULL,'entity',0,0,1);
INSERT INTO command_definitions VALUES('entity.find_parent','Find Parent',NULL,'entity',0,0,1);
INSERT INTO command_definitions VALUES('entity.find_radius','Find Radius',NULL,'entity',0,0,1);
INSERT INTO command_definitions VALUES('entity.find_self','Find Self',NULL,'entity',0,0,1);
INSERT INTO command_definitions VALUES('entity.find_status','Find Status',NULL,'entity',0,0,1);
INSERT INTO command_definitions VALUES('entity.nudge','Nudge',NULL,'entity',0,0,1);
INSERT INTO command_definitions VALUES('entity.set_battery_charge','Set Battery Charge',NULL,'entity',0,0,1);
INSERT INTO command_definitions VALUES('entity.spawn','Spawn',NULL,'entity',0,0,1);
INSERT INTO command_definitions VALUES('entity.spawngrid','Spawngrid',NULL,'entity',0,0,1);
INSERT INTO command_definitions VALUES('entity.spawnitem','Spawnitem',NULL,'entity',0,0,1);
INSERT INTO command_definitions VALUES('entity.spawnlootfrom','Spawnlootfrom',NULL,'entity',0,0,1);
INSERT INTO command_definitions VALUES('env.addtime','Addtime',NULL,'env',0,0,1);
INSERT INTO command_definitions VALUES('events.print_server_events','Print Server Events',NULL,'events',0,0,1);
INSERT INTO command_definitions VALUES('events.set_event_enabled','Set Event Enabled',NULL,'events',0,0,1);
INSERT INTO command_definitions VALUES('events.set_event_max_delay','Set Event Max Delay',NULL,'events',0,0,1);
INSERT INTO command_definitions VALUES('events.set_event_min_delay','Set Event Min Delay',NULL,'events',0,0,1);
INSERT INTO command_definitions VALUES('eventschedule.killallevents','Killallevents',NULL,'eventschedule',0,0,1);
INSERT INTO command_definitions VALUES('eventschedule.triggerevent','Triggerevent',NULL,'eventschedule',0,0,1);
INSERT INTO command_definitions VALUES('farmableanimal.simhours','Simhours','Simulates the provided number of hours on all farm animals within 10m','farmableanimal',0,0,1);
INSERT INTO command_definitions VALUES('gamemode.set','Set',NULL,'gamemode',0,0,1);
INSERT INTO command_definitions VALUES('gamemode.setteam','Setteam',NULL,'gamemode',0,0,1);
INSERT INTO command_definitions VALUES('gc.alloc','Alloc',NULL,'gc',0,0,1);
INSERT INTO command_definitions VALUES('gc.collect','Collect',NULL,'gc',0,0,1);
INSERT INTO command_definitions VALUES('gc.unload','Unload',NULL,'gc',0,0,1);
INSERT INTO command_definitions VALUES('global.add_wallpaper_radius','Add Wallpaper Radius','<name/id> <radius> | Use print_wallpaper_skins for a list | 0 -> default, -1 -> random','global',0,0,1);
INSERT INTO command_definitions VALUES('global.adminui_deleteugccontent','Adminui Deleteugccontent',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.adminui_fullrefresh','Adminui Fullrefresh',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.adminui_requestfireworkpattern','Adminui Requestfireworkpattern',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.adminui_requestplayerlist','Adminui Requestplayerlist',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.adminui_requestserverconvars','Adminui Requestserverconvars',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.adminui_requestserverinfo','Adminui Requestserverinfo',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.adminui_requestugccontent','Adminui Requestugccontent',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.adminui_requestugclist','Adminui Requestugclist',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.applygenes','Applygenes','<gene string> - Applies the given genes (e.g. "YYYGGG") to the clone/seed in your hands','global',0,0,1);
INSERT INTO command_definitions VALUES('global.authcount','Authcount','Returns all entities that the provided player is authed to (TC''s, locks, etc), supports --json','global',0,0,1);
INSERT INTO command_definitions VALUES('global.authradius','Authradius',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.authradius_multi','Authradius Multi',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.authradius_radius','Authradius Radius',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.ban','Ban','ban <player> <reason> [optional duration]','global',1,1,1);
INSERT INTO command_definitions VALUES('global.banid','Banid','banid <steamid> <username> <reason> [optional duration]','global',1,0,1);
INSERT INTO command_definitions VALUES('global.banlist','Banlist','List of banned users (sourceds compat)','global',1,0,1);
INSERT INTO command_definitions VALUES('global.banlistex','Banlistex','List of banned users - shows reasons and usernames','global',1,0,1);
INSERT INTO command_definitions VALUES('global.bans','Bans','List of banned users','global',1,0,1);
INSERT INTO command_definitions VALUES('global.breakclothing','Breakclothing',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.breakitem','Breakitem',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.buildinfo','Buildinfo','Get information about this build','global',0,0,1);
INSERT INTO command_definitions VALUES('global.carstats','Carstats','Get information about all the cars in the world','global',0,0,1);
INSERT INTO command_definitions VALUES('global.change_wallpaper_radius','Change Wallpaper Radius','<name/id> <radius> | Use print_wallpaper_skins for a list | 0 -> default, -1 -> random','global',0,0,1);
INSERT INTO command_definitions VALUES('global.clear_wallpaper_radius','Clear Wallpaper Radius','clear_wallpaper_radius <radius>','global',1,0,1);
INSERT INTO command_definitions VALUES('global.clearallsprays','Clearallsprays',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.clearallspraysbyplayer','Clearallspraysbyplayer',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.clearcontainer','Clearcontainer','clearcontainer: Removes all items inside the container you''re looking at','global',1,0,1);
INSERT INTO command_definitions VALUES('global.clearcontainer_radius','Clearcontainer Radius','clearcontainer_radius <radius>: Removes all items inside a container within a radius','global',1,0,1);
INSERT INTO command_definitions VALUES('global.cleardroppeditems','Cleardroppeditems',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.clearspraysatpositioninradius','Clearspraysatpositioninradius',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.clearspraysinradius','Clearspraysinradius',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.clearugcbyplayer','Clearugcbyplayer',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.clearugcentitiesinrange','Clearugcentitiesinrange',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.clearugcentity','Clearugcentity',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.clearvendingmachinenamescontaining','Clearvendingmachinenamescontaining',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.clientperf','Clientperf',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.colliders','Colliders',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.deauthradius','Deauthradius',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.deauthradius_multi','Deauthradius Multi',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.deauthradius_radius','Deauthradius Radius',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.dump','Dump',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.entcount','Entcount','Returns all entities that the provided player has placed, supports --json','global',0,0,1);
INSERT INTO command_definitions VALUES('global.entid','Entid',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.error','Error',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.fillcontainer','Fillcontainer','fillcontainer <optional: category> - Fills the container you are looking at with random items, can also specify a category (ammunition, weapon etc.)','global',0,0,1);
INSERT INTO command_definitions VALUES('global.fillcontainer_radius','Fillcontainer Radius','fillcontainer_radius <radius> <optional: category> - Fills containers with random items within a radius, can also specify a category','global',0,0,1);
INSERT INTO command_definitions VALUES('global.fillinventory','Fillinventory','fillinventory <optional: category> - Fills your inventory with random items, can also specify a category (ammunition, weapon etc.)','global',0,0,1);
INSERT INTO command_definitions VALUES('global.free','Free',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.getugcinfo','Getugcinfo',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.injure','Injure',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.injureplayer','Injureplayer',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.kick','Kick',NULL,'global',0,1,1);
INSERT INTO command_definitions VALUES('global.kickall','Kickall',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.kill','Kill',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.killallplayers','Killallplayers',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.killbees','Killbees','Kills all bee swarms','global',1,0,1);
INSERT INTO command_definitions VALUES('global.killplayer','Killplayer',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.listid','Listid','List of banned users, by ID (sourceds compat)','global',1,0,1);
INSERT INTO command_definitions VALUES('global.moderatorid','Moderatorid',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.mute','Mute',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.mutelist','Mutelist','Print a list of currently muted players','global',0,0,1);
INSERT INTO command_definitions VALUES('global.objects','Objects',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.ownerid','Ownerid',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.playerlist','Playerlist','Get a list of players','global',0,0,1);
INSERT INTO command_definitions VALUES('global.playerlistids','Playerlistids','Get a list of player''s IDs','global',0,0,1);
INSERT INTO command_definitions VALUES('global.players','Players','Print out currently connected clients etc','global',0,0,1);
INSERT INTO command_definitions VALUES('global.print_wallpaper_skins','Print Wallpaper Skins','Lists all wallpaper skins','global',0,0,1);
INSERT INTO command_definitions VALUES('global.printallscenesinbuild','Printallscenesinbuild',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.queue','Queue',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.quit','Quit',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.recover','Recover',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.recoverplayer','Recoverplayer',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.removemoderator','Removemoderator',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.removeowner','Removeowner',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.removeskipqueue','Removeskipqueue','Removes skip queue permission from a SteamID','global',1,0,1);
INSERT INTO command_definitions VALUES('global.report','Report',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.respawn','Respawn',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.respawn_sleepingbag','Respawn Sleepingbag',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.respawn_sleepingbag_remove','Respawn Sleepingbag Remove',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.restart','Restart',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.say','Say','Sends a message in chat','global',0,1,1);
INSERT INTO command_definitions VALUES('global.serverinfo','Serverinfo','Get a list of information about the server','global',0,0,1);
INSERT INTO command_definitions VALUES('global.setinfo','Setinfo',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.skick','Skick',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.skin_looking','Skin Looking','<skin>','global',0,0,1);
INSERT INTO command_definitions VALUES('global.skin_radius','Skin Radius','skin_radius ''skin'' ''radius''','global',0,0,1);
INSERT INTO command_definitions VALUES('global.skipqueue','Skipqueue',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.skipqueueid','Skipqueueid','Adds skip queue permissions to a SteamID','global',0,0,1);
INSERT INTO command_definitions VALUES('global.sleep','Sleep',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.sleepingusers','Sleepingusers','Show user info for players on server.','global',0,0,1);
INSERT INTO command_definitions VALUES('global.sleepingusersinrange','Sleepingusersinrange','Show user info for sleeping players on server in range of the player.','global',0,0,1);
INSERT INTO command_definitions VALUES('global.sleeptarget','Sleeptarget',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.spectate','Spectate',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.spectateid','Spectateid',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.stats','Stats','Print out stats of currently connected clients','global',0,0,1);
INSERT INTO command_definitions VALUES('global.status','Status','Print out currently connected clients','global',0,0,1);
INSERT INTO command_definitions VALUES('global.status_sv','Status Sv',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.steamrelayinit','Steamrelayinit',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.steamstatus','Steamstatus',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.subscriptions','Subscriptions',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.sysinfo','Sysinfo',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.sysuid','Sysuid',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.teaminfo','Teaminfo',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.teleport','Teleport',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.teleport2autheditem','Teleport2autheditem','<steamID/name> <optional: filter> - Teleport to a random entity the player is authed on','global',0,0,1);
INSERT INTO command_definitions VALUES('global.teleport2death','Teleport2death',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.teleport2grid','Teleport2grid',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.teleport2marker','Teleport2marker',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.teleport2me','Teleport2me',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.teleport2mission','Teleport2mission',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.teleport2nearest','Teleport2nearest',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.teleport2owneditem','Teleport2owneditem',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.teleportany','Teleportany',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.teleporteveryone2me','Teleporteveryone2me',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.teleportlos','Teleportlos',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.teleportnonsleepers2me','Teleportnonsleepers2me',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.teleportsleepers2me','Teleportsleepers2me',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.teleporttargetteam2me','Teleporttargetteam2me',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.teleportteam2me','Teleportteam2me',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.textures','Textures',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.togglespectateteaminfo','Togglespectateteaminfo',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.unban','Unban',NULL,'global',0,1,1);
INSERT INTO command_definitions VALUES('global.unmute','Unmute',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('global.updatemanifest','Updatemanifest','Immediately update the manifest','global',0,0,1);
INSERT INTO command_definitions VALUES('global.upgrade_looking','Upgrade Looking','<grade>','global',0,0,1);
INSERT INTO command_definitions VALUES('global.upgrade_radius','Upgrade Radius','upgrade_radius ''grade'' ''radius''','global',0,0,1);
INSERT INTO command_definitions VALUES('global.users','Users','Show user info for players on server.','global',0,0,1);
INSERT INTO command_definitions VALUES('global.usersinrange','Usersinrange','Show user info for players on server in range of the player.','global',0,0,1);
INSERT INTO command_definitions VALUES('global.usersinrangeofplayer','Usersinrangeofplayer','Show user info for players on server in range of the supplied player (eg. Jim 50)','global',0,0,1);
INSERT INTO command_definitions VALUES('global.version','Version',NULL,'global',0,0,1);
INSERT INTO command_definitions VALUES('growableentity.growall','Growall',NULL,'growableentity',0,0,1);
INSERT INTO command_definitions VALUES('growableentity.killall','Killall',NULL,'growableentity',0,0,1);
INSERT INTO command_definitions VALUES('handcuffs.togglecuffslocked','Togglecuffslocked',NULL,'handcuffs',0,0,1);
INSERT INTO command_definitions VALUES('harmony.load','Load',NULL,'harmony',0,0,1);
INSERT INTO command_definitions VALUES('harmony.unload','Unload',NULL,'harmony',0,0,1);
INSERT INTO command_definitions VALUES('heli.call','Call',NULL,'heli',0,0,1);
INSERT INTO command_definitions VALUES('heli.calltome','Calltome',NULL,'heli',0,0,1);
INSERT INTO command_definitions VALUES('heli.death','Death',NULL,'heli',0,0,1);
INSERT INTO command_definitions VALUES('heli.drop','Drop',NULL,'heli',0,0,1);
INSERT INTO command_definitions VALUES('heli.flee','Flee',NULL,'heli',0,0,1);
INSERT INTO command_definitions VALUES('heli.move','Move',NULL,'heli',0,0,1);
INSERT INTO command_definitions VALUES('heli.orbit','Orbit',NULL,'heli',0,0,1);
INSERT INTO command_definitions VALUES('heli.orbitstrafe','Orbitstrafe',NULL,'heli',0,0,1);
INSERT INTO command_definitions VALUES('heli.patrol','Patrol',NULL,'heli',0,0,1);
INSERT INTO command_definitions VALUES('heli.strafe','Strafe',NULL,'heli',0,0,1);
INSERT INTO command_definitions VALUES('heli.testpuzzle','Testpuzzle',NULL,'heli',0,0,1);
INSERT INTO command_definitions VALUES('hexagongridgenerator.generategrid','Generategrid','<gridSize> 5 <tileSpacing> 1.35','hexagongridgenerator',0,0,1);
INSERT INTO command_definitions VALUES('hierarchy.cd','Cd',NULL,'hierarchy',0,0,1);
INSERT INTO command_definitions VALUES('hierarchy.del','Del',NULL,'hierarchy',0,0,1);
INSERT INTO command_definitions VALUES('hierarchy.ls','Ls',NULL,'hierarchy',0,0,1);
INSERT INTO command_definitions VALUES('inventory.addownership','Addownership','Add ownership to item','inventory',0,0,1);
INSERT INTO command_definitions VALUES('inventory.clearinventory','Clearinventory','Clears the inventory of a target player. eg. inventory.clearInventory jim. Can take container names as arguments: --belt --wear --backpack','inventory',1,0,1);
INSERT INTO command_definitions VALUES('inventory.convertownership','Convertownership','Reduce ownership to item to allow new ownership to be added','inventory',0,0,1);
INSERT INTO command_definitions VALUES('inventory.copyto','Copyto','Copies the players inventory to the player in front of them','inventory',0,0,1);
INSERT INTO command_definitions VALUES('inventory.defs','Defs',NULL,'inventory',0,0,1);
INSERT INTO command_definitions VALUES('inventory.deployloadout','Deployloadout','Deploys the given loadout to a target player. eg. inventory.deployLoadout testloadout jim','inventory',0,0,1);
INSERT INTO command_definitions VALUES('inventory.deployloadoutinrange','Deployloadoutinrange','Deploys a loadout to players in a radius eg. inventory.deployLoadoutInRange testloadout 30','inventory',0,0,1);
INSERT INTO command_definitions VALUES('inventory.endloot','Endloot',NULL,'inventory',0,0,1);
INSERT INTO command_definitions VALUES('inventory.equipslot','Equipslot',NULL,'inventory',0,0,1);
INSERT INTO command_definitions VALUES('inventory.equipslottarget','Equipslottarget',NULL,'inventory',0,0,1);
INSERT INTO command_definitions VALUES('inventory.give','Give','{item} {amount} {condition} {skin} {container} {slot}','inventory',0,0,1);
INSERT INTO command_definitions VALUES('inventory.giveall','Giveall',NULL,'inventory',0,0,1);
INSERT INTO command_definitions VALUES('inventory.givearm','Givearm','{itemid} {amount}','inventory',0,0,1);
INSERT INTO command_definitions VALUES('inventory.givebp','Givebp',NULL,'inventory',0,0,1);
INSERT INTO command_definitions VALUES('inventory.giveid','Giveid','{itemid} {amount}','inventory',0,0,1);
INSERT INTO command_definitions VALUES('inventory.giveto','Giveto','{item} {player} {amount} {skin}','inventory',0,0,1);
INSERT INTO command_definitions VALUES('inventory.lighttoggle','Lighttoggle',NULL,'inventory',0,0,1);
INSERT INTO command_definitions VALUES('inventory.listloadouts','Listloadouts','Prints all saved inventory loadouts','inventory',0,0,1);
INSERT INTO command_definitions VALUES('inventory.pipetteid','Pipetteid',NULL,'inventory',0,0,1);
INSERT INTO command_definitions VALUES('inventory.reduceownership','Reduceownership','Reduce ownership to item to allow new ownership to be added','inventory',0,0,1);
INSERT INTO command_definitions VALUES('inventory.reloaddefs','Reloaddefs',NULL,'inventory',0,0,1);
INSERT INTO command_definitions VALUES('inventory.resetbp','Resetbp',NULL,'inventory',0,0,1);
INSERT INTO command_definitions VALUES('inventory.saveloadout','Saveloadout','Saves the current equipped loadout of the calling player. eg. inventory.saveLoadout loaduoutname','inventory',0,0,1);
INSERT INTO command_definitions VALUES('inventory.set_item_image','Set Item Image',NULL,'inventory',0,0,1);
INSERT INTO command_definitions VALUES('inventory.setwornarmorslots','Setwornarmorslots','Set worn items to have maximum armor slots supported','inventory',0,0,1);
INSERT INTO command_definitions VALUES('inventory.unlockall','Unlockall',NULL,'inventory',0,0,1);
INSERT INTO command_definitions VALUES('ioentity.debugqueue','Debugqueue',NULL,'ioentity',0,0,1);
INSERT INTO command_definitions VALUES('log.level','Level',NULL,'log',0,0,1);
INSERT INTO command_definitions VALUES('manifest.printmanifest','Printmanifest',NULL,'manifest',0,0,1);
INSERT INTO command_definitions VALUES('manifest.printmanifestraw','Printmanifestraw',NULL,'manifest',0,0,1);
INSERT INTO command_definitions VALUES('memsnap.full','Full',NULL,'memsnap',0,0,1);
INSERT INTO command_definitions VALUES('memsnap.managed','Managed',NULL,'memsnap',0,0,1);
INSERT INTO command_definitions VALUES('memsnap.native','Native',NULL,'memsnap',0,0,1);
INSERT INTO command_definitions VALUES('meta.add','Add','add <convar> <amount> - adds amount to convar','meta',0,0,1);
INSERT INTO command_definitions VALUES('metaldetectorsource.servercountsources','Servercountsources',NULL,'metaldetectorsource',0,0,1);
INSERT INTO command_definitions VALUES('networkprofiler.serverprofile','Serverprofile','networkprofiler.serverprofile [time to profile(in seconds), min(0.1), max(1000), float]','networkprofiler',0,0,1);
INSERT INTO command_definitions VALUES('nexus.broadcast_ping','Broadcast Ping',NULL,'nexus',0,0,1);
INSERT INTO command_definitions VALUES('nexus.ping','Ping',NULL,'nexus',0,0,1);
INSERT INTO command_definitions VALUES('nexus.playeronline','Playeronline',NULL,'nexus',0,0,1);
INSERT INTO command_definitions VALUES('nexus.refreshislands','Refreshislands',NULL,'nexus',0,0,1);
INSERT INTO command_definitions VALUES('nexus.transfer','Transfer',NULL,'nexus',0,0,1);
INSERT INTO command_definitions VALUES('nexus.uploadmap','Uploadmap','Reupload the map image to the nexus. Normally happens automatically at server boot. WARNING: This will lag the server!','nexus',0,0,1);
INSERT INTO command_definitions VALUES('note.update','Update',NULL,'note',0,0,1);
INSERT INTO command_definitions VALUES('npcvendingmachine.addhours','Addhours','Simulates the provided number of hours passing in the vending machine system','npcvendingmachine',0,0,1);
INSERT INTO command_definitions VALUES('npcvendingmachine.printallpricechanges','Printallpricechanges','Print out all current price changes on the server','npcvendingmachine',0,0,1);
INSERT INTO command_definitions VALUES('npcvendingmachine.resetdynamicpricing','Resetdynamicpricing','Resets the state of all discounts and surcharges from NPC vending machines','npcvendingmachine',0,0,1);
INSERT INTO command_definitions VALUES('npcvendingmachine.resetfrequencytags','Resetfrequencytags',NULL,'npcvendingmachine',0,0,1);
INSERT INTO command_definitions VALUES('physics.getbounds','Getbounds',NULL,'physics',0,0,1);
INSERT INTO command_definitions VALUES('physics.print_colliders_per_cell','Print Colliders Per Cell',NULL,'physics',0,0,1);
INSERT INTO command_definitions VALUES('physics.print_colliders_per_prefab','Print Colliders Per Prefab',NULL,'physics',0,0,1);
INSERT INTO command_definitions VALUES('physics.setbounds','Setbounds','(center vec3) (extents vec3)','physics',0,0,1);
INSERT INTO command_definitions VALUES('player.abandonmission','Abandonmission',NULL,'player',0,0,1);
INSERT INTO command_definitions VALUES('player.cinematic_gesture','Cinematic Gesture',NULL,'player',0,0,1);
INSERT INTO command_definitions VALUES('player.cinematic_play','Cinematic Play',NULL,'player',0,0,1);
INSERT INTO command_definitions VALUES('player.cinematic_stop','Cinematic Stop',NULL,'player',0,0,1);
INSERT INTO command_definitions VALUES('player.copyrotation','Copyrotation',NULL,'player',0,0,1);
INSERT INTO command_definitions VALUES('player.createskull','Createskull',NULL,'player',0,0,1);
INSERT INTO command_definitions VALUES('player.createtrophy','Createtrophy',NULL,'player',0,0,1);
INSERT INTO command_definitions VALUES('player.dismount','Dismount',NULL,'player',0,0,1);
INSERT INTO command_definitions VALUES('player.fillwater','Fillwater','<fresh/salt/rads> - Fills up liquid container items in your hotbar as well as any liquid containers you are looking at','player',0,0,1);
INSERT INTO command_definitions VALUES('player.gesture_radius','Gesture Radius',NULL,'player',0,0,1);
INSERT INTO command_definitions VALUES('player.gesture_radius_notme','Gesture Radius Notme',NULL,'player',0,0,1);
INSERT INTO command_definitions VALUES('player.gotosleep','Gotosleep',NULL,'player',0,0,1);
INSERT INTO command_definitions VALUES('player.markhostile','Markhostile',NULL,'player',0,0,1);
INSERT INTO command_definitions VALUES('player.mount','Mount',NULL,'player',0,0,1);
INSERT INTO command_definitions VALUES('player.printpresence','Printpresence',NULL,'player',0,0,1);
INSERT INTO command_definitions VALUES('player.printstats','Printstats',NULL,'player',0,0,1);
INSERT INTO command_definitions VALUES('player.ragdoll','Ragdoll','optional param {player}','player',0,0,1);
INSERT INTO command_definitions VALUES('player.ragdollall','Ragdollall','ragdolls','player',0,0,1);
INSERT INTO command_definitions VALUES('player.ragdollallbutme','Ragdollallbutme','ragdolls everyone except player','player',0,0,1);
INSERT INTO command_definitions VALUES('player.ragdollother','Ragdollother','Ragdolls a player you''re looking at','player',0,0,1);
INSERT INTO command_definitions VALUES('player.reloadweapons','Reloadweapons',NULL,'player',0,0,1);
INSERT INTO command_definitions VALUES('player.resetmissions','Resetmissions','Resets the saved missions progress of the given player','player',0,0,1);
INSERT INTO command_definitions VALUES('player.resetmissions_all','Resetmissions All','Resets the saved missions progress of all player states on this server (online and offline players). Must be entered as "resetmissions_all Y" to execute.','player',0,0,1);
INSERT INTO command_definitions VALUES('player.resetstate','Resetstate','Resets the PlayerState of the given player','player',0,0,1);
INSERT INTO command_definitions VALUES('player.stopgesture_radius','Stopgesture Radius',NULL,'player',0,0,1);
INSERT INTO command_definitions VALUES('player.swapseat','Swapseat',NULL,'player',0,0,1);
INSERT INTO command_definitions VALUES('player.trigger_wildlife_trap','Trigger Wildlife Trap',NULL,'player',0,0,1);
INSERT INTO command_definitions VALUES('player.unloadweapons','Unloadweapons',NULL,'player',0,0,1);
INSERT INTO command_definitions VALUES('player.wakeup','Wakeup',NULL,'player',0,0,1);
INSERT INTO command_definitions VALUES('player.wakeupall','Wakeupall',NULL,'player',0,0,1);
INSERT INTO command_definitions VALUES('playerboat.kill_all_above_block_count','Kill All Above Block Count',NULL,'playerboat',0,0,1);
INSERT INTO command_definitions VALUES('playerboat.kill_all_above_deployable_count','Kill All Above Deployable Count',NULL,'playerboat',0,0,1);
INSERT INTO command_definitions VALUES('playerboat.kill_io_deployables','Kill Io Deployables','Kills any IO entities deployed on boats. Not a fast command. Use sparingly when needed.','playerboat',1,0,1);
INSERT INTO command_definitions VALUES('playerboat.kill_nonconvex_deployables','Kill Nonconvex Deployables','Kills any entities deployed on boats with non-convex colliders. Not a fast command. Use sparingly when needed.','playerboat',1,0,1);
INSERT INTO command_definitions VALUES('playerboat.lookatdragbyangle','Lookatdragbyangle',NULL,'playerboat',0,0,1);
INSERT INTO command_definitions VALUES('playerboat.print_nonconvex','Print Nonconvex','Prints a list of boats with non-convex collider deployables. Not a fast command. Use sparingly when needed.','playerboat',0,0,1);
INSERT INTO command_definitions VALUES('playerboat.print_stats','Print Stats',NULL,'playerboat',0,0,1);
INSERT INTO command_definitions VALUES('playerboat.setsailsopen','Setsailsopen',NULL,'playerboat',0,0,1);
INSERT INTO command_definitions VALUES('playerboat.sink','Sink',NULL,'playerboat',0,0,1);
INSERT INTO command_definitions VALUES('pool.clear_assets','Clear Assets',NULL,'pool',0,0,1);
INSERT INTO command_definitions VALUES('pool.clear_memory','Clear Memory',NULL,'pool',0,0,1);
INSERT INTO command_definitions VALUES('pool.clear_prefabs','Clear Prefabs',NULL,'pool',0,0,1);
INSERT INTO command_definitions VALUES('pool.export_prefabs','Export Prefabs',NULL,'pool',0,0,1);
INSERT INTO command_definitions VALUES('pool.fill_prefabs','Fill Prefabs',NULL,'pool',0,0,1);
INSERT INTO command_definitions VALUES('pool.print_arraypool','Print Arraypool',NULL,'pool',0,0,1);
INSERT INTO command_definitions VALUES('pool.print_assets','Print Assets',NULL,'pool',0,0,1);
INSERT INTO command_definitions VALUES('pool.print_memory','Print Memory',NULL,'pool',0,0,1);
INSERT INTO command_definitions VALUES('pool.print_prefabs','Print Prefabs',NULL,'pool',0,0,1);
INSERT INTO command_definitions VALUES('pool.reset_max_pool_counter','Reset Max Pool Counter',NULL,'pool',0,0,1);
INSERT INTO command_definitions VALUES('profile.countsyncmoveentities','Countsyncmoveentities',NULL,'profile',0,0,1);
INSERT INTO command_definitions VALUES('profile.dump_profile_recorders','Dump Profile Recorders',NULL,'profile',0,0,1);
INSERT INTO command_definitions VALUES('profile.flush_analytics','Flush Analytics',NULL,'profile',0,0,1);
INSERT INTO command_definitions VALUES('profile.perfsnapshot','Perfsnapshot','profile.perfsnapshot [delay=15, int] [name=''Profile'', str, no extension, max 32chars] [frames=10, int, max 10] [debug=false, dumps a binary snapshot as well]','profile',0,0,1);
INSERT INTO command_definitions VALUES('profile.perfsnapshot_stream','Perfsnapshot Stream','profile.perfsnapshot_stream [name=''Profile'', str, no extension, max 32chars] [MainCap=32, int, max 256, buffer size for Main thread in Megabytes] [WorkerCap=8, int, max 256, buffer size for each Worker thread in Megabytes] [debug=false, dumps a binary snapshot as well]','profile',0,0,1);
INSERT INTO command_definitions VALUES('profile.resetexportinterval','Resetexportinterval',NULL,'profile',0,0,1);
INSERT INTO command_definitions VALUES('profile.start','Start',NULL,'profile',0,0,1);
INSERT INTO command_definitions VALUES('profile.stop','Stop',NULL,'profile',0,0,1);
INSERT INTO command_definitions VALUES('profile.stopwatchingallocs','Stopwatchingallocs','Stops tracking of allocations','profile',1,0,1);
INSERT INTO command_definitions VALUES('profile.watchallocs','Watchallocs','Params: [Name = ''Allocs''] [maxStackDepth = 16].','profile',0,0,1);
INSERT INTO command_definitions VALUES('rcon.ban_ip','Ban Ip','Ban an IP address from RCON, preventing it from connecting and kick any clients from this IP, this is permanent and persistent','rcon',1,0,1);
INSERT INTO command_definitions VALUES('rcon.clear_rcon_failed_logins','Clear Rcon Failed Logins','Clear all failed login attempts','rcon',1,0,1);
INSERT INTO command_definitions VALUES('rcon.clear_subscribers','Clear Subscribers','Clears all subscribers from the server.','rcon',1,0,1);
INSERT INTO command_definitions VALUES('rcon.print_rcon_bans','Print Rcon Bans','Print a table of permanently banned IPs and networks. Use ''--json'' to return a JSON object','rcon',1,0,1);
INSERT INTO command_definitions VALUES('rcon.print_rcon_clients','Print Rcon Clients','Print a table of connected RCON clients. Use ''--json'' to return a JSON object','rcon',0,0,1);
INSERT INTO command_definitions VALUES('rcon.print_rcon_failed_logins','Print Rcon Failed Logins','Print a table of clients with failed passwords.  Use ''--json'' to return a JSON object','rcon',0,0,1);
INSERT INTO command_definitions VALUES('rcon.subscribe','Subscribe','Un/Subscribes the current RCON connection to changes in server state. This could be a performance hit and should only be used if you need it.','rcon',0,0,1);
INSERT INTO command_definitions VALUES('rcon.unban_ip','Unban Ip','Unban an IP address from connecting to RCON, will also remove all attempt history','rcon',1,0,1);
INSERT INTO command_definitions VALUES('relationshipmanager.acceptinvite','Acceptinvite',NULL,'relationshipmanager',0,0,1);
INSERT INTO command_definitions VALUES('relationshipmanager.addtoteam','Addtoteam',NULL,'relationshipmanager',0,0,1);
INSERT INTO command_definitions VALUES('relationshipmanager.createandaddtoteam','Createandaddtoteam',NULL,'relationshipmanager',0,0,1);
INSERT INTO command_definitions VALUES('relationshipmanager.fakeinvite','Fakeinvite',NULL,'relationshipmanager',0,0,1);
INSERT INTO command_definitions VALUES('relationshipmanager.forceaddtoteam','Forceaddtoteam','Adds a player to a team whether they are on the server or not','relationshipmanager',0,0,1);
INSERT INTO command_definitions VALUES('relationshipmanager.kickmember','Kickmember',NULL,'relationshipmanager',0,0,1);
INSERT INTO command_definitions VALUES('relationshipmanager.leaveteam','Leaveteam',NULL,'relationshipmanager',0,0,1);
INSERT INTO command_definitions VALUES('relationshipmanager.promote','Promote',NULL,'relationshipmanager',0,0,1);
INSERT INTO command_definitions VALUES('relationshipmanager.promote_id','Promote Id',NULL,'relationshipmanager',0,0,1);
INSERT INTO command_definitions VALUES('relationshipmanager.rejectinvite','Rejectinvite',NULL,'relationshipmanager',0,0,1);
INSERT INTO command_definitions VALUES('relationshipmanager.sendinvite','Sendinvite',NULL,'relationshipmanager',0,0,1);
INSERT INTO command_definitions VALUES('relationshipmanager.sendofflineinvite','Sendofflineinvite',NULL,'relationshipmanager',0,0,1);
INSERT INTO command_definitions VALUES('relationshipmanager.sleeptoggle','Sleeptoggle',NULL,'relationshipmanager',0,0,1);
INSERT INTO command_definitions VALUES('relationshipmanager.trycreateteam','Trycreateteam',NULL,'relationshipmanager',0,0,1);
INSERT INTO command_definitions VALUES('relationshipmanager.wipe_all_contacts','Wipe All Contacts',NULL,'relationshipmanager',0,0,1);
INSERT INTO command_definitions VALUES('relationshipmanager.wipecontacts','Wipecontacts',NULL,'relationshipmanager',0,0,1);
INSERT INTO command_definitions VALUES('render.print_global_entities','Print Global Entities','Print off count of global building entities on the server','render',0,0,1);
INSERT INTO command_definitions VALUES('render.tree_entities','Tree Entities',NULL,'render',0,0,1);
INSERT INTO command_definitions VALUES('ridablehorse.ragdoll','Ragdoll',NULL,'ridablehorse',0,0,1);
INSERT INTO command_definitions VALUES('ridablehorse.setforsale','Setforsale',NULL,'ridablehorse',0,0,1);
INSERT INTO command_definitions VALUES('ridablehorse.sethorsebreed','Sethorsebreed',NULL,'ridablehorse',0,0,1);
INSERT INTO command_definitions VALUES('santasleigh.drop','Drop',NULL,'santasleigh',0,0,1);
INSERT INTO command_definitions VALUES('server.backup','Backup','Backup server folder','server',0,0,1);
INSERT INTO command_definitions VALUES('server.botcount','Botcount',NULL,'server',0,0,1);
INSERT INTO command_definitions VALUES('server.broadcastplayvideo','Broadcastplayvideo',NULL,'server',0,0,1);
INSERT INTO command_definitions VALUES('server.cheatreport','Cheatreport',NULL,'server',0,0,1);
INSERT INTO command_definitions VALUES('server.clear_bushes_radius','Clear Bushes Radius',NULL,'server',0,0,1);
INSERT INTO command_definitions VALUES('server.clear_loot_spawn_cache','Clear Loot Spawn Cache','Clears the loot spawn cache used to restrict loot into each era','server',1,0,1);
INSERT INTO command_definitions VALUES('server.clear_trees_radius','Clear Trees Radius',NULL,'server',0,0,1);
INSERT INTO command_definitions VALUES('server.clearplayerreportcounts','Clearplayerreportcounts','Clear the player reports list','server',1,0,1);
INSERT INTO command_definitions VALUES('server.combatlog','Combatlog','Get the player combat log','server',0,0,1);
INSERT INTO command_definitions VALUES('server.combatlog_outgoing','Combatlog Outgoing','Get the player combat log, only showing outgoing damage','server',0,0,1);
INSERT INTO command_definitions VALUES('server.corpseinfo','Corpseinfo','Get info on player corpses on the server','server',0,0,1);
INSERT INTO command_definitions VALUES('server.enforce_era_restrictions','Enforce Era Restrictions','Deletes items on the server that are not allowed in the era','server',1,0,1);
INSERT INTO command_definitions VALUES('server.fillchickencoop','Fillchickencoop',NULL,'server',0,0,1);
INSERT INTO command_definitions VALUES('server.fps','Fps',NULL,'server',0,0,1);
INSERT INTO command_definitions VALUES('server.listplayerreportcounts','Listplayerreportcounts','List the amount of reports players on the server have received','server',0,0,1);
INSERT INTO command_definitions VALUES('server.listtoolcupboards','Listtoolcupboards','Prints all the Tool Cupboards on the server','server',0,0,1);
INSERT INTO command_definitions VALUES('server.listvendingmachines','Listvendingmachines','Prints all the vending machines on the server','server',0,0,1);
INSERT INTO command_definitions VALUES('server.netprotocol','Netprotocol',NULL,'server',0,0,1);
INSERT INTO command_definitions VALUES('server.packetlog','Packetlog',NULL,'server',0,0,1);
INSERT INTO command_definitions VALUES('server.player_state_cache_count','Player State Cache Count',NULL,'server',0,0,1);
INSERT INTO command_definitions VALUES('server.player_state_cache_evictions','Player State Cache Evictions',NULL,'server',0,0,1);
INSERT INTO command_definitions VALUES('server.playerlistpos','Playerlistpos','Prints the position of all players on the server','server',0,0,1);
INSERT INTO command_definitions VALUES('server.printdecryptqueue','Printdecryptqueue',NULL,'server',0,0,1);
INSERT INTO command_definitions VALUES('server.printeyes','Printeyes','Print the current player eyes.','server',0,0,1);
INSERT INTO command_definitions VALUES('server.printpos','Printpos','Print the current player position.','server',0,0,1);
INSERT INTO command_definitions VALUES('server.printposcenter','Printposcenter','Print the current player center position.','server',0,0,1);
INSERT INTO command_definitions VALUES('server.printreadqueue','Printreadqueue',NULL,'server',0,0,1);
INSERT INTO command_definitions VALUES('server.printrot','Printrot','Print the current player rotation.','server',0,0,1);
INSERT INTO command_definitions VALUES('server.printwipeid','Printwipeid','Prints the current wipe id of the sav','server',1,0,1);
INSERT INTO command_definitions VALUES('server.printwritequeue','Printwritequeue',NULL,'server',0,0,1);
INSERT INTO command_definitions VALUES('server.readcfg','Readcfg',NULL,'server',0,0,1);
INSERT INTO command_definitions VALUES('server.resetrespawns','Resetrespawns','Clear all static respawn points','server',1,0,1);
INSERT INTO command_definitions VALUES('server.resetserveremoji','Resetserveremoji','Rescans the serveremoji folder, note that clients will need to reconnect to get the latest emoji','server',0,0,1);
INSERT INTO command_definitions VALUES('server.rpclog','Rpclog',NULL,'server',0,0,1);
INSERT INTO command_definitions VALUES('server.save','Save','Force save the current game','server',0,1,1);
INSERT INTO command_definitions VALUES('server.sendnetworkupdate','Sendnetworkupdate','Send network update for all players','server',0,0,1);
INSERT INTO command_definitions VALUES('server.setshowholstereditems','Setshowholstereditems','Show holstered items on player bodies','server',0,0,1);
INSERT INTO command_definitions VALUES('server.snapshot','Snapshot','This sends a snapshot of all the entities in the client''s pvs. This is mostly redundant, but we request this when the client starts recording a demo.. so they get all the information.','server',0,0,1);
INSERT INTO command_definitions VALUES('server.start','Start','Starts a server','server',0,1,1);
INSERT INTO command_definitions VALUES('server.stop','Stop','Stops a server','server',1,1,1);
INSERT INTO command_definitions VALUES('server.unlockrespawns','Unlockrespawns','Unlock all static respawn points','server',0,0,1);
INSERT INTO command_definitions VALUES('server.writecfg','Writecfg','Writes config files','server',0,0,1);
INSERT INTO command_definitions VALUES('serverocclusion.occlusionvalidategroups','Occlusionvalidategroups',NULL,'serverocclusion',0,0,1);
INSERT INTO command_definitions VALUES('serverocclusion.serverocclusiondebug','Serverocclusiondebug','Tests occlusion visibility between two positions','serverocclusion',0,0,1);
INSERT INTO command_definitions VALUES('sleepingbag.assigntoplayer','Assigntoplayer',NULL,'sleepingbag',0,0,1);
INSERT INTO command_definitions VALUES('sleepingbag.clearfromplayer','Clearfromplayer',NULL,'sleepingbag',0,0,1);
INSERT INTO command_definitions VALUES('spawn.cargoshipdockingtest','Cargoshipdockingtest',NULL,'spawn',0,0,1);
INSERT INTO command_definitions VALUES('spawn.cargoshipevent','Cargoshipevent',NULL,'spawn',0,0,1);
INSERT INTO command_definitions VALUES('spawn.ch47event','Ch47event',NULL,'spawn',0,0,1);
INSERT INTO command_definitions VALUES('spawn.delete_all_populations','Delete All Populations',NULL,'spawn',0,0,1);
INSERT INTO command_definitions VALUES('spawn.delete_populations','Delete Populations',NULL,'spawn',0,0,1);
INSERT INTO command_definitions VALUES('spawn.dump_map','Dump Map',NULL,'spawn',0,0,1);
INSERT INTO command_definitions VALUES('spawn.fill_groups','Fill Groups',NULL,'spawn',0,0,1);
INSERT INTO command_definitions VALUES('spawn.fill_individuals','Fill Individuals',NULL,'spawn',0,0,1);
INSERT INTO command_definitions VALUES('spawn.fill_populations','Fill Populations',NULL,'spawn',0,0,1);
INSERT INTO command_definitions VALUES('spawn.report','Report',NULL,'spawn',0,0,1);
INSERT INTO command_definitions VALUES('spawn.scalars','Scalars',NULL,'spawn',0,0,1);
INSERT INTO command_definitions VALUES('spawn.simulate_loot','Simulate Loot','<iterations> - Simulates a number of iterations on the closest loot container and sums up the items spawned','spawn',0,0,1);
INSERT INTO command_definitions VALUES('spawn.svshielddummy','Svshielddummy',NULL,'spawn',0,0,1);
INSERT INTO command_definitions VALUES('stability.refresh_stability','Refresh Stability',NULL,'stability',0,0,1);
INSERT INTO command_definitions VALUES('supply.call','Call',NULL,'supply',0,0,1);
INSERT INTO command_definitions VALUES('supply.drop','Drop',NULL,'supply',0,0,1);
INSERT INTO command_definitions VALUES('system.cpu_affinity','Cpu Affinity',NULL,'system',0,0,1);
INSERT INTO command_definitions VALUES('system.cpu_priority','Cpu Priority',NULL,'system',0,0,1);
INSERT INTO command_definitions VALUES('telephonemanager.printallphones','Printallphones',NULL,'telephonemanager',0,0,1);
INSERT INTO command_definitions VALUES('travellingvendor.spawn','Spawn',NULL,'travellingvendor',0,0,1);
INSERT INTO command_definitions VALUES('travellingvendor.startevent','Startevent',NULL,'travellingvendor',0,0,1);
INSERT INTO command_definitions VALUES('triggerbase.clearexcludelayers','Clearexcludelayers',NULL,'triggerbase',0,0,1);
INSERT INTO command_definitions VALUES('triggerbase.setexcludelayers','Setexcludelayers',NULL,'triggerbase',0,0,1);
INSERT INTO command_definitions VALUES('tutorialisland.debugislandpositions','Debugislandpositions',NULL,'tutorialisland',0,0,1);
INSERT INTO command_definitions VALUES('vddraw.setisrecording','Setisrecording',NULL,'vddraw',0,0,1);
INSERT INTO command_definitions VALUES('vehicle.autohover','Autohover',NULL,'vehicle',0,0,1);
INSERT INTO command_definitions VALUES('vehicle.boatdriftinfo','Boatdriftinfo','Print out boat drift status for all boats','vehicle',0,0,1);
INSERT INTO command_definitions VALUES('vehicle.fixcars','Fixcars','Fixes up vehicles within 10m of the player by repairing to full hp, adding fuel to engines, and more','vehicle',0,0,1);
INSERT INTO command_definitions VALUES('vehicle.killboats','Killboats',NULL,'vehicle',0,0,1);
INSERT INTO command_definitions VALUES('vehicle.killcars','Killcars',NULL,'vehicle',0,0,1);
INSERT INTO command_definitions VALUES('vehicle.killdrones','Killdrones',NULL,'vehicle',0,0,1);
INSERT INTO command_definitions VALUES('vehicle.killminis','Killminis',NULL,'vehicle',0,0,1);
INSERT INTO command_definitions VALUES('vehicle.killmotorbikes','Killmotorbikes',NULL,'vehicle',0,0,1);
INSERT INTO command_definitions VALUES('vehicle.killpushbikes','Killpushbikes',NULL,'vehicle',0,0,1);
INSERT INTO command_definitions VALUES('vehicle.killscraphelis','Killscraphelis',NULL,'vehicle',0,0,1);
INSERT INTO command_definitions VALUES('vehicle.killtrains','Killtrains',NULL,'vehicle',0,0,1);
INSERT INTO command_definitions VALUES('vehicle.stop_all_trains','Stop All Trains',NULL,'vehicle',0,0,1);
INSERT INTO command_definitions VALUES('vehicle.swapseats','Swapseats',NULL,'vehicle',0,0,1);
INSERT INTO command_definitions VALUES('vehicle.swaptoseat','Swaptoseat',NULL,'vehicle',0,0,1);
INSERT INTO command_definitions VALUES('vendingmachine.clearallvendingcustomerhistory','Clearallvendingcustomerhistory','Wipe the backend customer stats data on all vending machines. Slow operation.','vendingmachine',1,0,1);
INSERT INTO command_definitions VALUES('vendingmachine.clearallvendinghistory','Clearallvendinghistory','Wipe the backend stats data on all vending machines. Slow operation.','vendingmachine',1,0,1);
INSERT INTO command_definitions VALUES('voice.togglevoicerangeboost','Togglevoicerangeboost','Enabled/disables voice range boost for a player eg. ToggleVoiceRangeBoost sam 1','voice',0,0,1);
INSERT INTO command_definitions VALUES('waypointrace.startrace','Startrace',NULL,'waypointrace',0,0,1);
INSERT INTO command_definitions VALUES('weather.list_cloud_configs','List Cloud Configs',NULL,'weather',0,0,1);
INSERT INTO command_definitions VALUES('weather.load','Load',NULL,'weather',0,0,1);
INSERT INTO command_definitions VALUES('weather.load_cloud_config','Load Cloud Config',NULL,'weather',0,0,1);
INSERT INTO command_definitions VALUES('weather.report','Report',NULL,'weather',0,0,1);
INSERT INTO command_definitions VALUES('weather.reset','Reset',NULL,'weather',0,0,1);
INSERT INTO command_definitions VALUES('weather.reset_cloud_config','Reset Cloud Config',NULL,'weather',0,0,1);
INSERT INTO command_definitions VALUES('wipetimer.printtimezones','Printtimezones',NULL,'wipetimer',0,0,1);
INSERT INTO command_definitions VALUES('wipetimer.printwipe','Printwipe',NULL,'wipetimer',0,0,1);
INSERT INTO command_definitions VALUES('workshop.print_approved_skins','Print Approved Skins',NULL,'workshop',0,0,1);
INSERT INTO command_definitions VALUES('world.drawbounds','Drawbounds',NULL,'world',0,0,1);
INSERT INTO command_definitions VALUES('world.monuments','Monuments',NULL,'world',0,0,1);
INSERT INTO command_definitions VALUES('world.renderlabs','Renderlabs','Renders a PNG of the current map''s underwater labs, for a specific floor','world',0,0,1);
INSERT INTO command_definitions VALUES('world.rendermap','Rendermap','Renders a high resolution PNG of the current map','world',0,0,1);
INSERT INTO command_definitions VALUES('world.rendertunnels','Rendertunnels','Renders a PNG of the current map''s tunnel network','world',0,0,1);
INSERT INTO command_definitions VALUES('xmas.refill','Refill',NULL,'xmas',0,0,1);
INSERT INTO command_definitions VALUES('ziplinelaunchpoint.highlight','Highlight',NULL,'ziplinelaunchpoint',0,0,1);
INSERT INTO command_definitions VALUES('ziplinelaunchpoint.report','Report',NULL,'ziplinelaunchpoint',0,0,1);
COMMIT;
